version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5005:5005"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    networks:
      - app_network

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
