version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myRootUser
      MONGO_INITDB_ROOT_PASSWORD: myPassword

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myRootUser
      ME_CONFIG_MONGODB_ADMINPASSWORD: myPassword
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      - mongodb

  app:
    build: .
    container_name: profile-page
    restart: always
    ports:
      - "1337:1337"
    depends_on:
      - mongodb
    environment:
      - DBURL=mongodb://myRootUser:myPassword@mongodb:27017
      - HOST=0.0.0.0
      - PORT=1337

volumes:
  mongo-data: